- local_action:
    module: ec2_elb_lb
    name: "{{app_name}}-ELB"
    security_group_ids: ['{{elb_security_group}}']
    state: present
    region: "{{elb_region}}"
    subnets: "{{elb_subnet}}"
    listeners: "{{elb_listeners}}"
  register: elb

- debug:
    msg: "{{elb}}"